emailText = "ashiq.qups@gmail.com"
passwordText = "Asdfgh123456"
postBtn = "com.bikroy:id/btn_post"  # id
# homeBtn = By.ID("com.bikroy:id/main_bottom_panel_home")
search_icon = "com.bikroy:id/main_bottom_panel_search"  # id
# chatBtn = By.ID("com.bikroy:id/main_bottom_panel_chat")
profileBtn = "com.bikroy:id/main_bottom_panel_my_account"
# activityClose = By.ID("com.bikroy:id/register_activity_close")
sign_in_email_btn = "com.bikroy:id/sign_in_sign_up_email_button"
emailField = "com.bikroy:id/sign_in_email"  # id
passwordField = "com.bikroy:id/sign_in_password"  # id
loginBtn = "com.bikroy:id/register_register_button"  # id
# noAccountBtn = By.ID("com.bikroy:id/register_have_account_text")
# signUpBtn = By.ID("com.bikroy:id/register_signup_button")
# forgotPassBtn = By.ID("com.bikroy:id/register_forgot_password")
logoutBtn = "com.bikroy:id/my_account_logout"  # id
# confirmPassField = By.ID("পাসওয়ার্ড আবার")
# nameText = "Abir"
# signupEmailText = "abir.qups@gmail.com"
# signUpPasswordText = "Asdfgh123456"
myAds = "com.bikroy:id/my_account_my_ads"
myMembership = "com.bikroy:id/my_account_my_membership"
favorites = "com.bikroy:id/my_account_favorites"
myProfile = "com.bikroy:id/my_account_my_resume"
backButton = "android.widget.ImageButton"  # class_name
# headingElements = By.ID("android.widget.TextView")
# adSliderItems = By.ID("android.widget.FrameLayout")
editSearchField = "com.bikroy:id/edit_search"
searchBox = "com.bikroy:id/search_verticals"  # id
intro_close_btn = "com.bikroy:id/intro_close"